import type { Metadata } from "next";
import LegalPageLayout, { type LegalSection } from "../../components/qattan/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms of Service | Qattan AI",
  description: "The terms governing your use of the Qattan AI platform.",
};

const sections: LegalSection[] = [
  {
    heading: "1. Nature of the Output",
    body: [
      "Images generated by Qattan AI are AI-powered conceptual architectural visualizations. They are NOT certified engineering drawings and must not be relied upon for construction, structural, or code-compliance purposes. Always consult a licensed architect or engineer before any real-world execution.",
    ],
  },
  {
    heading: "2. Credits & Billing",
    body: [
      "Every registered account receives 10 free credits that renew automatically every 24 hours. Each successful generation deducts exactly one credit. Credit balances are maintained server-side and hold no cash value.",
    ],
  },
  {
    heading: "3. Acceptable Use",
    body: [
      "You must not use the platform for any illegal purpose, including infringing intellectual property, generating misleading real-estate marketing of properties you do not represent, or uploading content you have no right to use.",
      "We reserve the right to suspend accounts that abuse the service or attempt to manipulate the credit system.",
    ],
  },
  {
    heading: "4. Service Modifications",
    body: [
      "Qattan AI reserves the right to modify, suspend, or discontinue any part of the service — including tools, credit allowances, and renewal rules — at any time. Material changes will be announced on the platform.",
    ],
  },
  {
    heading: "5. Disclaimer & Liability",
    body: [
      "The service is provided \"as is\" without warranties of any kind. To the maximum extent permitted by law, Qattan AI is not liable for any damages arising from the use of, or reliance on, generated outputs.",
    ],
  },
];

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      subtitle="The rules that govern your use of Qattan AI."
      effectiveLabel="Effective date: September 2026"
      backLabel="Back to home"
      sections={sections}
    />
  );
}
